import fs from 'node:fs/promises'
import WebSocket from 'file:///C:/Users/CarryWho/.dsh/profiles/web/node_modules/ws/wrapper.mjs'
const page=(await fetch('http://127.0.0.1:9353/json').then(r=>r.json())).find(p=>p.type==='page'&&p.url.includes('3080'))
const ws=new WebSocket(page.webSocketDebuggerUrl);let seq=0,pending=new Map()
ws.on('message',raw=>{const m=JSON.parse(String(raw));if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)}})
await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject)})
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
const wait=ms=>new Promise(r=>setTimeout(r,ms));await send('Runtime.enable')
await ev(`localStorage.setItem('dsh.theme.preference.v1',JSON.stringify({version:1,theme:'cutout-clash-night',owner:'dsh-theme-cutout-clash'}));localStorage.setItem('dsh-theme-cutout-clash.motion','full');location.reload()`);await wait(1600)
await ev(`document.querySelector('[aria-label="打开侧边栏"]')?.click()`);await wait(300)
const states=await ev(`(()=>{const info=e=>{if(!e)return null;const c=getComputedStyle(e);return{text:(e.textContent||'').replace(/\\s+/g,' ').trim().slice(0,100),color:c.color,bg:c.backgroundColor,shadow:c.boxShadow,selected:e.getAttribute('aria-selected'),expanded:e.getAttribute('aria-expanded')}};return{expanded:[...document.querySelectorAll('[data-pane="sidebar"] [role="treeitem"][aria-expanded="true"]')].map(info),selected:[...document.querySelectorAll('[data-pane="sidebar"] [role="treeitem"][aria-selected="true"]')].map(info),produced:[...document.querySelectorAll('[data-produced-files-row]')].slice(0,3).map(info),tokens:{hover:getComputedStyle(document.body).getPropertyValue('--dsw-alias-interactive-bg-hover').trim(),floatingHover:getComputedStyle(document.body).getPropertyValue('--dsw-alias-button-floating-hover').trim()}}})()`)
await ev(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='设置');b?.click();return !!b})()`);await wait(500)
const pos=await ev(`(()=>{const e=[...document.querySelectorAll('[role="dialog"][aria-modal="true"] button')].find(b=>b.getAttribute('aria-current')!=='true');if(!e)return null;const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`)
if(pos){await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:pos.x,y:pos.y});await wait(150)}
const settingsHover=await ev(`(()=>{const e=[...document.querySelectorAll('[role="dialog"][aria-modal="true"] button')].find(b=>b.matches(':hover'));if(!e)return null;const c=getComputedStyle(e);return{text:(e.textContent||'').trim(),color:c.color,bg:c.backgroundColor,hover:e.matches(':hover')}})()`)
await ev(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='Pop Signal');b?.click();return !!b})()`);await wait(70)
const transition=await ev(`(()=>{const root=document.getElementById('dsh-cutout-runtime-transition-root'),plate=root?.firstElementChild,dialog=document.querySelector('[role="dialog"][aria-modal="true"]'),r=root?.getBoundingClientRect(),d=dialog?.getBoundingClientRect();return{root:root?{z:getComputedStyle(root).zIndex,position:getComputedStyle(root).position,rect:{x:r.x,y:r.y,w:r.width,h:r.height}}:null,plate:plate?{stage:plate.getAttribute('data-stage'),visibility:getComputedStyle(plate).visibility}:null,dialog:dialog?{z:getComputedStyle(dialog.parentElement).zIndex,rect:{x:d.x,y:d.y,w:d.width,h:d.height}}:null,coversDialog:!!(r&&d&&r.x<=d.x&&r.y<=d.y&&r.right>=d.right&&r.bottom>=d.bottom)}})()`)
await wait(500);const settled=await ev(`(()=>({theme:document.body.getAttribute('data-cutout-clash'),curtain:!!document.getElementById('dsh-cutout-transition-root'),runtimeStage:document.querySelector('#dsh-cutout-runtime-transition-root .cc-plate')?.getAttribute('data-stage')||null,frame:!!document.querySelector('[data-dsh-frame]')}))()`)
const out={states,settingsHover,transition,settled};await fs.writeFile('D:/Resources/DSH_PRJ/DevPlugins/dsh-theme-cutout-clash/artifacts/validation-v050.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));ws.close()
